services:
  gitea:
    image: gitea/gitea:1.21.11
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__server__DOMAIN=localhost
      - GITEA__server__ROOT_URL=http://localhost:3003/
    volumes:
      - ./gitea:/data
    ports:
      - "3003:3000"   # Web UI
      - "2222:22"     # SSH
    restart: unless-stopped
